name: Update Flex endpoint

on:
    push:
        branches:
            - main

defaults:
    run:
        shell: bash

jobs:
    call-flex-update:
        uses: specter-global/symfony-recipes/.github/workflows/callable-flex-update.yaml@main
        with:
            versions_json: .github/versions.json
